import React, { useEffect, useState } from 'react';
import { Search, Check, X, Trash2, ShieldAlert } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { getLocalComments, updateLocalCommentStatus, deleteLocalComment, readerAuthEnabled } from '../../lib/reader';

const statuses = ['pending', 'approved', 'rejected', 'spam'];
export default function AdminComments() {
    const [comments, setComments] = useState([]);
    const [status, setStatus] = useState('pending');
    const [search, setSearch] = useState('');
    const [message, setMessage] = useState('');
    const load = async () => { if (!readerAuthEnabled) { setComments(getLocalComments().filter(comment => status === 'all' || comment.status === status)); return; } const query = supabase.from('comments').select('id,post_id,content,status,author_display_name,created_at').order('created_at', { ascending: false }); if (status !== 'all') query.eq('status', status); const { data, error } = await query; if (error) setMessage(`Moderation requires a Supabase-authenticated admin: ${error.message}`); else setComments(data || []); };
    useEffect(() => {
        // Moderation data is external state and may arrive after the filter changes.
        load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [status]);
    const moderate = async (id, nextStatus) => { if (!readerAuthEnabled) { updateLocalCommentStatus(id, nextStatus); load(); return; } const { error } = await supabase.from('comments').update({ status: nextStatus }).eq('id', id); if (error) setMessage(error.message); else load(); };
    const remove = async (id) => { if (!readerAuthEnabled) { deleteLocalComment(id); load(); return; } const { error } = await supabase.from('comments').delete().eq('id', id); if (error) setMessage(error.message); else load(); };
    const visible = comments.filter(comment => !search || `${comment.author_display_name} ${comment.content}`.toLowerCase().includes(search.toLowerCase()));
    return <div><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-4xl font-black tracking-tighter" style={{ fontFamily: '"Bebas Neue", Impact, sans-serif' }}>Comments</h1><p className="mt-1 text-sm text-white/40">Review reader conversations before they appear publicly.</p></div><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white"><option value="all">All statuses</option>{statuses.map(value => <option key={value} value={value}>{value}</option>)}</select></div><div className="relative mb-6"><Search size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/30" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search comments..." className="w-full rounded-xl border border-white/10 bg-[#0a0a0f] py-3 pl-11 pr-4 text-sm text-white outline-none" /></div>{message && <div className="mb-6 flex gap-3 rounded-xl border border-yellow-400/20 bg-yellow-400/5 p-4 text-sm text-yellow-200"><ShieldAlert size={18} />{message}</div>}<div className="space-y-3">{visible.map(comment => <article key={comment.id} className="rounded-2xl border border-white/10 bg-[#0a0a0f] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-white">{comment.author_display_name || 'Reader'}</p><p className="mt-1 text-xs text-white/35">Post {comment.post_id} · {new Date(comment.created_at).toLocaleString()}</p></div><span className="rounded-lg bg-white/5 px-2 py-1 text-xs font-bold uppercase text-white/50">{comment.status}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed text-white/70">{comment.content}</p><div className="mt-4 flex flex-wrap gap-2">{comment.status !== 'approved' && <button onClick={() => moderate(comment.id, 'approved')} className="flex items-center gap-1 rounded-lg bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-300"><Check size={13} />Approve</button>}{comment.status !== 'rejected' && <button onClick={() => moderate(comment.id, 'rejected')} className="flex items-center gap-1 rounded-lg bg-yellow-400/10 px-3 py-2 text-xs font-bold text-yellow-300"><X size={13} />Reject</button>}{comment.status !== 'spam' && <button onClick={() => moderate(comment.id, 'spam')} className="rounded-lg bg-red-400/10 px-3 py-2 text-xs font-bold text-red-300">Mark spam</button>}<button onClick={() => remove(comment.id)} className="flex items-center gap-1 rounded-lg bg-white/5 px-3 py-2 text-xs font-bold text-white/50"><Trash2 size={13} />Delete</button></div></article>)}{visible.length === 0 && <p className="py-16 text-center text-sm text-white/35">No comments in this view.</p>}</div></div>;
}
